# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  winboat = {
    pname = "winboat";
    version = "v0.7.3";
    src = fetchFromGitHub {
      owner = "TibixDev";
      repo = "winboat";
      rev = "v0.7.3";
      fetchSubmodules = false;
      sha256 = "sha256-9Cb62AInb+896vYbvtacKfSx0qhflZTb8/gTL6iUyhw=";
    };
  };
}
